### ISSUE TITLE
cv2 TypeError: src data type = 0 is not supported

### ISSUE THREAD

**Issue by alexwang3322** [sujithv28/Deep-Leafsnap#2]
Hi, I got this error in first step 'python dataset.py'

```
[INFO]  Training Samples : 23598
	Testing Samples  :  5900
[INFO] Processing Images
Height: 469, Width:  700

Traceback (most recent call last):
  File "dataset.py", line 114, in <module>
    csv_name='leafsnap-dataset-train-images.csv', augment=True)
  File "dataset.py", line 80, in save_images
    image_to_write = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
```

The source code and dataset is from where your docs, please tell here, if you have any answer.

**Comment by MahmoudMadoo** [comment]
I got it too, anyone can help
